### ISSUE TITLE
Question: What does "Land reservations" in the `CONTRIBUTING_DATA.md` file mean?

### ISSUE THREAD

**Issue by yeozy95** [Open-Earth-Foundation/OpenClimate#16]
In the `CONTRIBUTING_DATA.md` file, it was noted that Land reservations data are a type of data included and needed for OpenClimate.

Is there further documentation on what "Land reservations" data refer to, and where it would fit within the [OpenClimate Data Schema](https://github.com/Open-Earth-Foundation/OpenClimate-Schema)?

**Comment by evanp** [comment]
So, I tried to come up with a term for [LULUSF](https://unfccc.int/topics/land-use/workstreams/land-use--land-use-change-and-forestry-lulucf) that wasn't so formal, and that was my best result! Maybe we should just say "LULUSF" or expand the acronym in the document?

As far as where that stuff goes, I'm not actually sure. We've talked about using it in emissions breakdowns, either by sector or some other way. Another option would be in the Action table, which we still need to dig into.
