### ISSUE TITLE
having trouble setting up a local dev environment

### ISSUE THREAD

**Issue by sfishel18** [Open-Earth-Foundation/OpenClimate#171]
👋 hello! this is a great project and i'd really like to become a contributor.

i'm trying to set up a local dev environment following the docs and so far not able to so. i've gotten as far as launching the frontend and the api locally with the former pointed to the latter, but i'm getting errors like this in the api:

```
{"level":"error","message":"Could not find sites by id in the database:  connect ECONNREFUSED ::1:5432","metadata":{"module":"/Users/simonfishel/opt/git/OpenClimate/api/orm/sites.ts","name":"SequelizeConnectionRefusedError","original":{"address":"::1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"parent":{"address":"::1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"service":"OpenClimate-hub-controller","stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n    at Client._connectionCallback (/Users/simonfishel/opt/git/OpenClimate/api/node_modules/sequelize/src/dialects/postgres/connection-manager.js:179:24)\n    at Client._handleErrorWhileConnecting (/Users/simonfishel/opt/git/OpenClimate/api/node_modules/pg/lib/client.js:318:19)\n    at Client._handleErrorEvent (/Users/simonfishel/opt/git/OpenClimate/api/node_modules/pg/lib/client.js:328:19)\n    at Connection.emit (node:events:513:28)\n    at Connection.emit (node:domain:489:12)\n    at Socket.reportStreamError (/Users/simonfishel/opt/git/OpenClimate/api/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)"}}
```

so i'm guessing i need to also have a database running, but can't find any instructions on how to do that. 

could you provide some instructions on the standard flow for local development? it can be high-level, i'm happy to figure out the details myself as part of learning about the tech stack. and if you're up for it i could send you a PR with updates to the contributing docs. thanks!

**Comment by lemilonkh** [comment]
Hi :)
Which operating system are you using? 
I've put together a PR with scripts and documentation for running k8s locally on Linux, which you can find here:

#167

**Comment by sfishel18** [comment]
oh great, i missed that `k8s` directory, but it's what i was looking for, thanks! i'm on a mac, so looks like i should be all set.

out of curiosity, if i'm just making changes to the frontend, is it possible/recommended to point it to the production api instead of running all of the services locally?

**Comment by lemilonkh** [comment]
Yes that's possible, I've done the same thing. You should be able to replace the value of `api` in [server.environment.ts](https://github.com/Open-Earth-Foundation/OpenClimate/blob/develop/ui/src/shared/environments/server.environments.ts), which is used for all API requests the frontend makes.
